export const OwnerSchema = {
  firstName: "",
  lastName: "",
  pass1: "",
  pass2: "",
  birthDate: "",        
  username: "",  
  gender: "",        
  email: "",
  address: "",
  phone: "",
  landline:"",
  amka:"",
  afm:"",
  adress:"",
  location:"",
  post:"",
  idnumber:"",
};